services:
  - type: web
    name: vocalysis-api
    env: docker
    plan: free
    autoDeploy: true
    rootDir: .
    dockerfilePath: api/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "8080"
      - key: BACKEND_CORS_ORIGINS
        value: "*"
